# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
# "Be sure to follow the issue template!"
newIssueWelcomeComment: >
  Thank you for opening your first issue here!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
# "Please check out our contributing guidelines."
newPRWelcomeComment: >
  Thank you for opening this pull request!

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
# It is recommended to include as many gifs and emojis as possible!
firstPRMergeComment: >
  Congrats on merging of your first pull request!
